# Generated by Django 5.0.1 on 2024-02-13 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quedada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quedadas_creadas', to=settings.AUTH_USER_MODEL)),
                ('participantes', models.ManyToManyField(related_name='quedadas_participantes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
